BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20

WINDOW_WIDTH  = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE
EMPTY_TILE = 0

# SOLDIER
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3   # the upper part
SOLDIER_FEET_ROWS = 1   # the lower part
SOLDIER = 3

# FLAG
FLAG_ROWS = 3
FLAG_COLS = 4

flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS
FLAG = 2

# MINES
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
MINE = 1



# COLORS
GREEN = (0, 163, 7)
BLACK = (0, 0, 0)

# SCREEN
BACKGROUND_COLOR = GREEN
BACKGROUND_COLOR_XRAY = BLACK
# grass
NUM_OF_GRASS = 20
# img paths
GRASS_IMG_PATH = r"images/grass.png"
# xrays
XRAY_LINE_WIDTH = 1
XRAY_LINE_COLOR = GREEN