import copy
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE
EMPTY_TILE = 0

MINE = 1
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

FLAG_ROWS = 3
FLAG_COLS = 4
flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS
FLAG = 2

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3
SOLDIER_FEET_ROWS = 1
SOLDIER = 3

SOLDIER_LEGS_ROW_START = 3
SOLDIER_LEFT_LEG_COL_START = 0
SOLIDER_BODY_COL_START = 0
SOLDIER_BODY_ROW_START = 0

soldier_legs_row = copy.copy(SOLDIER_LEGS_ROW_START)
soldier_left_leg_col = copy.copy(SOLDIER_LEFT_LEG_COL_START)
soldier_body_col_start = copy.copy(SOLIDER_BODY_COL_START)
soldier_body_row_start = copy.copy(SOLDIER_BODY_ROW_START)
