import copy
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20

WINDOW_WIDTH  = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE
EMPTY_TILE = 0

# SOLDIER
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3   # the upper part
SOLDIER_FEET_ROWS = 1   # the lower part
SOLDIER = 3

SOLDIER_LEGS_ROW_START = 3
SOLDIER_LEFT_LEG_COL_START = 0
SOLIDER_BODY_COL_START = 0
SOLDIER_BODY_ROW_START = 0

soldier_legs_row = copy.copy(SOLDIER_LEGS_ROW_START)
soldier_left_leg_col = copy.copy(SOLDIER_LEFT_LEG_COL_START)
soldier_body_col_start = copy.copy(SOLIDER_BODY_COL_START)
soldier_body_row_start = copy.copy(SOLDIER_BODY_ROW_START)


# FLAG
FLAG_HEIGHT = 3
FLAG_WIDTH = 4

FLAG_ROWS = BOARD_ROWS - FLAG_HEIGHT
FLAG_COLS = BOARD_COLS - FLAG_WIDTH
FLAG = 2

# MINES
MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
MINE = 1

# COLORS
GREEN = (0, 163, 7)
BLACK = (0, 0, 0)
ORANGE = (255, 202, 58)

# SCREEN
# background
BACKGROUND_COLOR = GREEN
BACKGROUND_COLOR_XRAY = BLACK
# grass
NUM_OF_GRASS = 20
# img paths
GRASS_IMG_PATH = r"images/grass.png"
MINE_IMG_PATH = R"images/mine.png"
SOLIDER_IMG_PATH = r"images/soldier.png"
NIGHT_SOLIDER_IMG_PATH = r"images/soldier_night.png"
FLAG_IMG_PATH = r"images/flag.png"
# xrays
XRAY_LINE_WIDTH = 1
XRAY_LINE_COLOR = GREEN
# fonts
FONT_NAME = "Calibri"
FONT_SIZE = 30
# win
WIN_MESSAGE_LOCATION =(0.4 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (FONT_SIZE / 2))
WIN_MESSAGE = "You Won !!!"
WIN_MESSAGE_COLOR = ORANGE
# lose
LOSE_MESSAGE_LOCATION =(0.4 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (FONT_SIZE / 2))
LOSE_MESSAGE = "You Lost :("
LOSE_MESSAGE_COLOR = ORANGE


# GAME STATES
RUNNING_STATE = 0
LOSE_STATE = -1
WIN_STATE = 1

END_GAME_TIMEOUT = 3

# SAVING

SAVING_FILES_PATH = "save_file_{key}.json"